apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: songbot
stringData:
    #ENC[AES256_GCM,data:UVETkDnFsS7qQJrTYhfLcY7JSvfpHc/xoLbziW3HZsggnf2r,iv:g/BxjmKhNdkw625cQ8XJeFonr9+QP+zBYTc5j4EcMoA=,tag:EkMH7NYhGX7zaL/6epF1PA==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:cN7Rv9wAVKKnpbZafLBXLnqrldsn+GR8hUP/IQG+/ZqITbaW5kNHxNtg3dv3FA==,iv:lIx+fbfwlAVtbr1hr0Wopg3SxE6KExeJOyrZJ0J0zGM=,tag:zH/9n7+gzk4EaDmlLJMjug==,type:str]
    #ENC[AES256_GCM,data:D9OAsYrsPZeNO/fNrfCjOnODvIkXHdkLrW3EPCjdN88AN2wObHjysd+pWhVgrTd3MrCRG1Ck7c2e91VsefSP/fB9eXQRuw==,iv:0TUjEXudGHDvin4WUYfXJ+NEDzxnDJXAzMGuS/tjzgI=,tag:tFdO02wXCDsLn7EN8kq43Q==,type:comment]
    ALLOWED_USERS: ENC[AES256_GCM,data:+bhiAZ9brPrsLg1PU0QOzlUjqg==,iv:AT8F5ivbJW+Wic3H9h41rTyyDlwFREcid140g/UOjsw=,tag:BZQYQAiWgOgECrZemP7Eyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1djlCVXczOEdqNWN5ekMx
            N2NpRHJSMHAxVDQyaDVCbUJnZjdKa1pJaFZvClZQalhEaVl2Q3gxTmVHYTYrVElU
            WjA1YVYvUDNxdkR0aGtJZkVPR2craTAKLS0tIGZjVnRTZStlRUNEZVR2bmNsWSt6
            QlRZc2xoQVR3aWU2VUN3bk5YWTJiZ2MKq3f2IxmoHsjYnJwRXBo/yH7JPw/m4ZMc
            N34g3SEee/JxSRyxYRKalxwWcI3AiErTmJEbu4i17l49Hkvt0EZhkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTHNhVVZlT3JoRU5LZTNP
            VHpzcSswOGVRWDZJL2VxaWhpWmYybXF0ZjFvCmVhaHFad1hyUUdJUUtJd1NMa0dX
            bm5PUVhwRnRnMElNOFMzZ3VyQmdqdUEKLS0tIFJpOWRhODlEdHVvN1BBRFJzZXFo
            M1ZDMXZaNWVHTjljOUxybkNaNkRtMXcKNgGvwcof0uxuei2Wsb30b3YHB5dl0Z+n
            Y55r/eWjwQdGHLQnN/RwR2FQisBEHd0FS02dDvRoEDTAI2n9O1fATw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T17:30:53Z"
    mac: ENC[AES256_GCM,data:t+BEbHawMObxvPP1JqaXyUcu5OUGeH7Pz0r0rZMORvoJ60XMc3a0avP/CJSZt9oMYu+W9FUmUCPbENjVIrCpcGnsdPTEjjBTiGqRVkcpN2JSVYEp9lk4hogmckgRF0ogSuBYJfEK/6epGmmlFWn7Orm72ZUGxXl8vA5e/cwEKZY=,iv:GkIrVyWxjIJt9q3boHVx1kaZh3rqThtucG7AUC49T/M=,tag:KK2HwtQRQTBlhjF1ZqrL9w==,type:str]
    version: 3.13.3
