apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:AbcHsMUzwusJ1w98j5Hgw5kppJ/3jG+fv6MY0HbHBwjZCNZm+Hc9Lp1EVBVF9oKXj4+7f25ayF4YpR9KMiDTTjnP9gQmSspuH52wjKP7ZG/FQYjoLo8dKYUekLnOrDpun+1lj+KjZVFG9D7ItFnU6JOHjt9B/16wtvfxoeqZQqCy/PnDI4YqlvKT5aySB0PuGwVawk0hiZqc/lksg0HVqHW+yUmhdMnkgDM13mHjr1+3Kh/n6P7160ddtBTMFQYSkEt+jR8oleaxmxwdErZyr4ReFCp5XhhKtYvoYs2nQq5RrisC4VGX68UzUQLNGsrw1zWo8H0o0V9whSafdc0CRbqkoQicUk+1rmY9ng==,iv:NA4Ng66YOryesjcmz7Q8Bok4gikGeDCapvy3nxW3RdU=,tag:jLssA619CUQxE7gJhFICHg==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: songbot
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSjlhakI4S25LdEcxS0tO
            Tk9DWTV2VGpTeG9OUnhEQlV5aERGTzBVQUU4CnpyYmhXSHlYTWhKbHpRbHJtS0Rj
            T0lTeGJsUlY3SlFoaERtSENoZTFEZzAKLS0tIGVuVlFiNkthNWlESGlmWG56RU9h
            QzFMUzB0Y1RjT0NBQkhFaHQ1WG5YL0kKeK/TAlXlM0RVfrhrDgEESGRPzTEypDn6
            yDyPml4RsS6ydItXJXv9ryu3SGbKJ9PLyxLN2/HTMGXEC4PHQVcPhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuemVrcUIxalhRUE5QNm9C
            SUljZnpWT0ZDVzVhazh3ZzdwVFRjL0UwRWpZCmxYczZnc3BHZXRReFhLTktsc0N3
            dHIzR2VkNjZ4Nks2YTRBQmp0UkRRTlkKLS0tIFZuWDBvSTFEZzRQMVRGS1dGVmNn
            OHMwU3BJeUhsaG5ocDRJaFF5R2FUbmsK9trA4od6ULYPeNk2Q0qL0xJharuQHlqR
            LubEaoM9SMXXQctXqJV0IyUQk2rE3qONCl6FokqDbpNwiC2DD81kEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T17:31:07Z"
    mac: ENC[AES256_GCM,data:F0bu8XRgkqAZEjYiBOga21qyO9n4/tUigGTbdaD0HrJqeYUt8kYnfgM2c13eKVwA1LcrVn8NicqbDbeugHss3iME39W1wIpmTNzm402HmXO33gW7Nu0UtUuJ1htc4ejcOVSnruP3yyZ8opmb6mwZdZWckZ0siPGDuVIRe6UED/o=,iv:Zw7iY6eKuXa/JqKe3Y6MN4zKFGETT6amB1P3A+1K+zM=,tag:y86lXqGEvqHuGfoTYI4D5g==,type:str]
    version: 3.13.3
