apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: songbot
stringData:
    #ENC[AES256_GCM,data:RFKwBd9N+usShEi39IWpOMrBjDgwR8tj+yuMhnvs+2kTopHQ,iv:ZUofANApOExKvKTWHqP2QHw+jb6vgebmaAwd2ceQt/A=,tag:jLjMRuo2kBbypcbG8pCYAg==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:r7v3kW4fqsBt8BcT7hJoL+booBR0sdfS0tgEI5zQtND3CzYx2nFl2w3nv1J5kQ==,iv:a8WQPQfBEPRWgibJue1pVElnTjGZVD8GJWsgqCSChG0=,tag:aBX5Bf4GO6axq/b5a2Fckg==,type:str]
    #ENC[AES256_GCM,data:dSoa7kBtyjMcj34bbC3xWs34E9Swbm6akrUucvtL/5E2uKXdWu08+CBDnlzZmvbjIZRn9BMBGX/g3wzsPG67eJAm3x+i4Q==,iv:jORyCc0y67+ETLoB3kG6m8R4uWvg+LqZ+fPXX0yNJcY=,tag:N+zxvsbhWXhTJ5Fn4l7mcw==,type:comment]
    ALLOWED_USERS: ENC[AES256_GCM,data:fFFH7xB+NuuHfCkHlju8sxd2Nw==,iv:MazI0PhCmVdXcZqsbVEbn+iULz7iAQUWp44Zhv7zAqQ=,tag:fiGP0Y3XNFlFWXstAXZfkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmJaL212WUtiV0JlTENN
            WXAweFU4RURhREo1bERKWWRiNTA2ZE5ucXdjClRCdUlaMzlSbVAxaU1uV2RmdGlZ
            STVBQmhCcmdEejNCWEhIeXljdDgyVjgKLS0tIEtoQTQrRGY4ZisvTmlZY3p4d1ND
            bUpWSlVCa21mSXovR1NzRDhXdDdCaUUKv4UuoQIQ/Tqm/iVPZh5qdu3+Sl090+lI
            IHruH/63Dj2wGf+xamFP3wSRS7YcMxoxHTpk7oCz4rGO3gArRpVcjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU1czRFhrbzFsUlVzQWhw
            bEFNQlF4K2tYNWU4TnBHcUdVR3Z1UEZtQ3hBCjZNMk1BVVF6cDB1cEJBTDZxN0tz
            Sk9mdjFPSzhTcCsxWTZ4eTdSaTNJL00KLS0tIEw0L0hNc1dxM0Q5WnJKUXJxWmtH
            SWo1OGNka2xHS0RvVnpHR2xzR0hCYTAKCrNRiQl5XyZpTqeHRSpo3at4FUSX7RiU
            KzKTlXNGDdjrjJH03XJHFV3Zlf7JjAMdR7bsCLtL5CXn3b1O+dsm8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T17:46:51Z"
    mac: ENC[AES256_GCM,data:EOmFHuydy6Z8Pgjwp0YBBfiEFIsH8bHWRKMK9bIAu5s4CqF5opR1+YWm4ni9t20UBCKvzhhoLlHRIFV0CHAusjrELyRiV3roboY0hEWsGT8N0WO9zWlkdKg6wyIpCFSgJ4QiwacQ3LgECkPXL6/0lP1Cj3SCjdjSzi9VEzKBC54=,iv:Qsi4eaSKLCQGx/Uq6jXXQsxnc4rQxnxWfdNUi9BJ7zU=,tag:ddLxUjgaeK4soYK/PSbURw==,type:str]
    version: 3.13.3
