apiVersion: v1
kind: Secret
metadata:
    name: songbot
    namespace: songbot
stringData:
    #ENC[AES256_GCM,data:Pz28hVTKqmnsXwh9aYoURzWr8MISiVTX4WLmH97BSl4fE15G,iv:PLDHYpotYEmM3M3jSRbTOKkPaKePlQ6S1pS8lJFDMYY=,tag:vEPyeLA60+XVblOUZR4vfA==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:HW2giynT6lJ7lGvbTNgy3SyRXREobLmIhjmeEhOpFnJpfKexIezY/3KEkBzVsQ==,iv:Dacz3iVW+vunJ7U0mtS6EH4nIacI9gz/QVmfpBmVEYo=,tag:qmrIO3cahhIdGezCv0JT/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTklKZTB2T1o2b3BDUWRw
            R1dNVXptT0R4b200RE5RM1BhdlFGUnRZVG1RCmU1T2h6Y3hjYXYrU2ViY1o2Zlc1
            U2l4YzV5UFlxdksxQ25pdExsdEhmMk0KLS0tIC9IcGpQTWhWTnhZZ3RSUTJvS1NO
            ZUplV1QrWHJlRWFYY2pjZnNVVDRra3MKgX/+T8LS3tnPL68xC2x+y3HLXu5YOnRO
            jwzD4zBqMKR8sgeyhO4fPGswbEmuDpH4rfumIZa2thcBUY8HJaidug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T17:21:51Z"
    mac: ENC[AES256_GCM,data:75GdnscdpduSkVMj8FrwhiPRRT7dzN7kUs1aUli1SFZ0mAmAO4DEOFF/5zqge0W7qePAM8JnNA7XaLOZ7UHZHTJM9aMVCwBC+H8u0IjCKvZP/Ylx/7ijSR/A867iMOTZ0oOF/J1UHx+H+ao44v6iOvrD5EcUeUKXat9nScv7+D0=,iv:hswYWDp01rxPWvyf0dMYkrIvA6yhQuGnR9hdRKWtm4Q=,tag:MlPBPmI/yZ9zGzzpgM6l6g==,type:str]
    version: 3.13.3
