apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songbot
  namespace: songbot
  labels:
    app: songbot
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
